# fly.toml app configuration file generated for guides-d-a9vg on 2025-10-21T20:34:20Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'guides-d-a9vg'
primary_region = 'ams'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
